### ISSUE TITLE
Incorrect statistics 

### ISSUE THREAD

**Issue by waryak** [tarekziade/molotov#136] opened 2021-08-21 15:42 UTC
I have the simplest web-service and the simplest scenario, which return a lot of false-"FAILED" for requests, which were successfully processed.
The scenario is:
```@scenario(weight=100)
async def scenario_one(session):
    async with session.get(_API) as resp:
        print(resp.status, " ") # I print it out, to ensure that actual status is 200 for all requests
        assert resp.status == 200 or resp.status == 429
```
And output is:
```
**** Molotov v2.1. Happy breaking! ****
Preparing 1 worker...
OK
200  SSES: 0 | FAILURES: 0 | WORKERS: 1
200  SSES: 1 | FAILURES: 0 | WORKERS: 1
200  SSES: 2 | FAILURES: 1 | WORKERS: 1
200  SSES: 3 | FAILURES: 2 | WORKERS: 1
200  SSES: 4 | FAILURES: 3 | WORKERS: 1
200  SSES: 5 | FAILURES: 4 | WORKERS: 1
```
As you see, all requests returned 200, but most of them were marked as failed

**Comment by n1ngu** [comment] 2021-08-23 08:47
I think it is going to be very difficult to reproduce this. Would you please upload the minimal loadtest.py file that causes this as well as the full molotov CLI instruction with all the options you used?

Can you also share details about your platform? Python version, OS, list of installed dependencies, docker engine if one is involved and whatnot?

Also, what kind of API are you targeting? Is it a remote service? A local server? A webapp you developed? An existing http software of any kind? Does de problem reproduce if you target a simple-stupid webserver like the one you can startup running `python -m http.server 8888`?

**Comment by tarekziade** [comment] 2021-08-24 10:01
I think the problem might be related to the console because we print back on the same line. Try to print in a file to see if you get the same result. 

Maybe we could provide a special `print` function for this use case, that makes sure it prints on a new line

**Comment by tarekziade** [comment] 2022-10-22 03:36
I'll close it, feel free to reopen with more details

**Closed by tarekziade** 2022-10-22 03:36 UTC
